defaults: &defaults
  docker:
      - image: typelead/eta:latest
version: 2.1
jobs:
  build:
    <<: *defaults

    steps:
    - checkout

    - restore_cache:
        key: dhall-eta-cache-v1-

    - run: mv etlas.dhall etlas.dhall.skip
      
    - run: etlas update

    - run: etlas build

    - save_cache:
        key: dhall-eta-cache-v1-{{ epoch }}
        paths:
          - "~/.etlas/config"
          - "~/.etlas/packages"
          - "~/.etlas/store"
          - "~/.etlas/tools"

    - persist_to_workspace:
          root: .
          paths: .

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .
      
      - restore_cache:
          key: dhall-eta-cache-v1-

      - run: etlas build --enable-tests

      - save_cache:
          key: dhall-eta-cache-v1-{{ epoch }}
          paths:
            - "~/.etlas/config"
            - "~/.etlas/packages"
            - "~/.etlas/store"
            - "~/.etlas/tools"
            
      - run:
          name: Getting dhall-lang tests
          command: git clone https://github.com/dhall-lang/dhall-lang.git ../dhall-lang
      - run:
          name: Running tests
          command: etlas test
      
      
workflows:
  version: 2
  full_cycle:
    jobs:
      - build

      - test:
          requires:
            - build
