defaults: &defaults
  working_directory: ~/dhall-eta
  docker:
      - image: typelead/eta:latest
version: 2.0
jobs:
  build:
    <<: *defaults

    steps:
    - checkout

    - restore_cache:
        key: dhall-eta-cache-v2-

    - run: etlas update

    - run: etlas build

    - save_cache:
        key: dhall-eta-cache-v2-{{ checksum "etlas.dhall" }}
        paths:
          - "~/.etlas/config"
          - "~/.etlas/packages"
          - "~/.etlas/tools"
          - "~/.coursier"

    - persist_to_workspace:
          root: ~/
          paths:
            - dhall-eta
            - .etlas
            - .coursier
            - .eta

  test:
    <<: *defaults

    parallelism: 2

    steps:
      - attach_workspace:
          at: ~/
          
      - run:
          name: Building tests
          command: etlas build --enable-tests

      - run:
          name: Getting dhall-lang tests
          command: git clone --branch v$DHALL_STANDARD_VERSION --depth=1 https://github.com/jneira/dhall-lang.git ../dhall-lang
      - run:
          name: Running tests
          command: ./dist/build/eta-0.8.6.3/dhall-eta-0.1.0/t/tasty/build/tasty/tasty --hide-successes
            
workflows:
  version: 2
  full_cycle:
    jobs:
      - build

      - test:
          requires:
            - build
